version: '3'

services:

  db:
    container_name: db
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    command: -c "listen_addresses=*"
    ports:
      - "5432:5432"
    networks:
      - api-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: env/docker/api/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/api"
      - "/var/www/api/vendor"
    networks:
      - api-network
    depends_on:
      - db
    links:
      - db

networks:
  api-network:
    driver: bridge
