version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:7.2.33
    steps:
      - checkout
      - run: docker-compose up -d
      - run: env/scripts/docker_init.sh
#      - run: composer self-update
#      - restore_cache:
#          keys:
#            - composer-v1-{{ checksum "composer.lock" }}
#            - composer-v1-
#      - run: composer install
#      - save_cache:
#          key: composer-v1-{{ checksum "composer.lock" }}
#          paths:
#            - vendor
#      - persist_to_workspace:
#          root: ~/repo
#          paths:
#            - ./
#  test:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: ~/repo
#      - run: php artisan migrate:refresh --env=testing --database=test --seed
#      - run:
#          name: Testing Code
#          command: ./vendor/bin/phpunit --testdox

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
#      - test:
#          requires:
#            - build
